### ISSUE TITLE
Retain option missing on stork-deploy > 2.7.0

### ISSUE THREAD

**Issue by gimmebytes** [fizzed/stork#22]
Hi Joe,

how are you doing :-)

I started using stork-deploy to deploy our java apps and I really like it. It's so simple. Single dependency is Java. Goodbye ansible 👍 

I found a minor issue with the current version of stork-deploy. The changelog states (for version 2.6.0)

> stork-deploy: New retain option to only retain a specified number of past versions after a successful deploy.

but the option is missing when looking in the code. The DeployOptions class has already the field, but the DeployMain class is missing the parameter.

I could provide a PR if you like containing that little fix.

Cheers,
Marvin

**Comment by jjlauer** [comment]
Hey @gimmebytes -- I primarily use blaze scripts to programmatically do deploys so its a simple oversight to not have it in DeployMain.  A PR would be awesome!  You may want to check out using blaze, btw, to fire up stork deploys as well.

**Comment by gimmebytes** [comment]
Hi Joe,

will code that down and will open another PR.

Cheers,
Marvin
