### ISSUE TITLE
stork-fabric-deploy only work the first call, crash on second one

### ISSUE THREAD

**Issue by danielsawan** [fizzed/stork#4]
I tested stork-fabric-deploy from a linux env to a linux env.
stork-fabric-deploy -H root@192.168.0.10 --assembly target/test-1.0-SNAPSHOT.tar.gz

This work well the first time. The second push from serv1 to serv2 I got an error :

run: mkdir "test-1.0-SNAPSHOT"
run: rsync -at "/opt/test/version-1.0-20150303041435/" "/tmp/test-1.0-SNAPSHOT/" --exclude="conf" --exclude="data" --exclude="log" --exclude="run"
[localhost] local: expect -c 'exp_internal 0; set timeout 20; spawn rsync -avrtc --exclude=conf --delete  --force -e "ssh -oStrictHostKeyChecking=no -p 22" work/test-1.0-SNAPSHOT/ root@192.168.0.10:/tmp/test-1.0-SNAPSHOT/; expect "*?assword:*"; send "123456\n"; expect eof'
/bin/sh: 1: expect: not found
Fatal error: local() encountered an error (return code 127) while executing 'expect -c 'exp_internal 0; set timeout 20; spawn rsync -avrtc --exclude=conf --delete  --force -e "ssh -oStrictHostKeyChecking=no -p 22" work/test-1.0-SNAPSHOT/ root@192.168.0.10:/tmp/test-1.0-SNAPSHOT/; expect "*?assword:*"; send "123456\n"; expect eof''

The folder is created into the /opt/.. but seems like as there is an existing current symlink it was blocking.
the server is password protected so it ask me for the password when i used the command.

I also noticed things that i don't really agree with :
For example i noticed that you use the /tmp folder to extract the pushed tar but then don't remove it. So it can be easily explore from a hacker for example.
Second point is that the project is store in the /opt. It should be cool if we can configure that.

In my case i am using an environnement that is multi user. By that i mean i am developping an admin panel and push this panel to a server where other users have php file and can easily explore the hard disk.
I try to protect my file from reading and being potentially accessed by others. Having this tmp folder containing all those dangerous information and not cleaned just afraid me.
The /opt folder have the right to be read by other. (even if we can chmod o-rwx on in the project folder).
But this is another problem. The main problem is that stork-fabric-deploy only work the first time i execute the command.

**Comment by danielsawan** [comment]
oh for the part : 

"For example i noticed that you use the /tmp folder to extract the pushed tar but then don't remove it. So it can be easily explore from a hacker for example."

I just saw : https://github.com/fizzed/java-stork/issues/1

;)

**Comment by jjlauer** [comment]
Sure looks like the error is that "expect" command is not found on your local system.  Do you have expect installed?  What does "which expect" return on your local machine?

**Comment by danielsawan** [comment]
sorry but i maybe miss something then. I don't have any expect program installed on both server. I only installed stork command line toolk on the serv1 which i use to push the tar on serv2.

Is there something i didn't understand ? I read that it use Fabric, do i have to install fabric on both server ?

**Comment by jjlauer** [comment]
Ah, I know what is happening.

On the first brand new install, we tap into an scp command to install the
entire tarball.  Fabric can do that type of thing natively.  However, on
subsequent installs, to speed up deploys, we do a rsync to figure out what
changed.  Fabric can't do that very intelligently -- and "expect" is
required to get the password you're using to rsync.

Two ways to solve it:

1. Install expect.  It's a common program and yum/apt will have it.

2. Use password-less authentication.  If you can "rsync" or "ssh" w/o a
password (by properly setting up keys for example), then the "expect" part
will never occur w/ rsync.

I'll still mark this issue as a bug though since it'd be nice to have
"expect" searched for during an app run and the user is prompted to install
it.

**Comment by jjlauer** [comment]
BTW, this is all on your local/source machine -- NOT the target/remote.

**Comment by danielsawan** [comment]
No it is from a VPS server to another remote VPS server.
I just changed the IP adresse before the past in order to keep this private ;) (as password)

**Comment by danielsawan** [comment]
oh sorry i just notice that you was quoting something else. Forget my last response.

**Comment by danielsawan** [comment]
yep it work well now after installing expect. I agree you should mention it somewhere ;)
