### ISSUE TITLE
systemd instead of init

### ISSUE THREAD

**Issue by momiji** [fizzed/stork#5]
Hello,

I'm very interested in trying this one on my production servers for deploying, however I wonder if it was possible to choose between init and systemd, as my target is RHEL.

I'm using `type: CONSOLE`, so my service only has :

```
[Unit]
Description=myapp sample application
After=syslog.target network.target

[Service]
ExecStart=/opt/folder/myapp/bin/myapp

[Install]
WantedBy=multi-user.target
```

I think we should add `Restart=always` and of course application must be configure with `working_dir_mode: APP_HOME` !

Still need to find how to configure for `type: DAEMON`.

Other things that would be cool:
- chosse target folder, with default to /opt
- allow local deploy without sshing to the same server

What do you think ?

**Comment by jjlauer** [comment]
v2.2.0 is out and supports systemd as well as a few other enhancements.
