### ISSUE TITLE
Path problem when using --start

### ISSUE THREAD

**Issue by sermison** [fizzed/stork#6]
I am trying to use stork 2.0.0 in a ninja framework/maven based API project deployed to a staging environment on Ubuntu 14.04 with stork-deploy. When the application is about to start (at deploy or started by hand) I get the following errors:

```
Starting ContactApi: /opt/ContactAPI/current/bin/ContactApi: 806: /opt/ContactAPI/current/bin/ContactApi: cannot create /opt/ContactAPI/current//opt/ContactAPI/current/log/ContactApi.out: Directory nonexistent   
/opt/ContactAPI/current/bin/ContactApi: 808: /opt/ContactAPI/current/bin/ContactApi: cannot create /opt/ContactAPI/current//opt/ContactAPI/current/log/ContactApi.out: Directory nonexistent   
failed
```
The application is currently a snapshot version. Running it with "./ContactAPI --run" in the "/opt/ContactAPI/current/bin" directory is working fine. "./ContactAPI --start" in the same directory is showing the behaviour above.

Starting it in "/opt/ContactAPI/current" with "bin/ContactAPI --start" is also working nicely as well as a "bin/ContactAPI --stop".

Starting it with "service ContactAPI start" is showing the same errors.

I have no idea where to search for this problem. Any idea/hint?

**Comment by jjlauer** [comment]
What does your stork .yml config file look like?

**Comment by sermison** [comment]
I'm using this .yml
```
name: "ContactApi"
domain: "de.xempa"
display_name: "Contact API Service"  
short_description: "REST Service for X/C5 Contact API"  
type: DAEMON  
main_class: "ninja.standalone.NinjaJetty"  
platforms: [ LINUX ]  
working_dir_mode: RETAIN  
min_java_version: "1.8"  
symlink_java: true  
```
Thanks for having a look at it.

**Comment by jjlauer** [comment]
working_dir_mode: RETAIN

should be

working_dir_mode: APP_HOME

**Comment by sermison** [comment]
Great! That's it! Thank you for your fast response! And thanks for stork and especially for stork-deploy. It's a great tool improving our ninja-framework/gitlab-ci based workflow for developing our microservices.
